### PR TITLE
bunch of bug fixes

### PR DESCRIPTION
**Pull request by dgreisen-cfpb**

### CODE REVIEW

**Comment by dgreisen-cfpb** [comment]
@m3brown: please review when you get a chance.

**Comment by m3brown** [comment]
Do existing apps using this template need to manually copy the _security file after merging these changes?

**Comment by dgreisen-cfpb** [comment]
only if they want a security document. if the _security document is not found, then it is skipped.

**Comment by m3brown** [comment]
I'm getting errors on [this line](https://github.com/cfpb/pantheon-helpers/blob/master/src/couch_utils.iced#L102), where the value of security_data is undefined because the file identified by security_doc_path doesn't exist.

**Pull request merged**
