### PR TITLE
exponential backoff for failure retries

### PR DESCRIPTION
**Pull request by dgreisen-cfpb**

### CODE REVIEW

**Comment by m3brown** [comment]
:+1: looks good @dgreisen-cfpb

**Comment by marcesher** [comment]
189 files, 26,580 additions, and this gets nothing more than a :+1: ?!

Please tell me I'm missing the 12 hour code review that happened in the office :smirk_cat:

**Comment by dgreisen-cfpb** [comment]
@marcesher: It's only ~120 lines of actual code. The rest is tests, readme and checked in node modules. We spent several hours discussing the approach before I implemented it, and Mike asked me several clarifying questions offline while reviewing.

@m3brown: could you please merge?

**Comment by m3brown** [comment]
@marcesher _my approach to reviewing is "if it looks like code then it's probably bug free"._

**Pull request merged**
